spring.application.name=smart-community-server

server.port=8080

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/smart_community?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456

spring.data.redis.host=127.0.0.1
spring.data.redis.port=6378

mybatis-plus.configuration.map-underscore-to-camel-case=true

spring.sql.init.mode=never
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.sql.init.SqlInitializationAutoConfiguration

app.jwt.issuer=smart-community
app.jwt.secret=please-change-me
app.jwt.expire-seconds=7200
