CREATE DATABASE IF NOT EXISTS smart_community DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

USE smart_community;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS person;
DROP TABLE IF EXISTS camera;
DROP TABLE IF EXISTS community;
DROP TABLE IF EXISTS in_out_record;
DROP TABLE IF EXISTS visitor;
DROP TABLE IF EXISTS operation_log;
DROP TABLE IF EXISTS role_menu;
DROP TABLE IF EXISTS user_role;
DROP TABLE IF EXISTS menu;
DROP TABLE IF EXISTS role;
DROP TABLE IF EXISTS `user`;

CREATE TABLE `user` (
    user_id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '用户ID',
    username VARCHAR(50) NOT NULL COMMENT '用户名',
    password VARCHAR(200) NOT NULL COMMENT '密码',
    real_name VARCHAR(50) DEFAULT NULL COMMENT '真实姓名',
    mobile VARCHAR(20) DEFAULT NULL COMMENT '手机号',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0-禁用，1-启用',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0-未删除，1-已删除',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';

CREATE TABLE role (
    role_id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '角色ID',
    role_name VARCHAR(50) NOT NULL COMMENT '角色名称',
    role_code VARCHAR(50) NOT NULL COMMENT '角色编码',
    description VARCHAR(200) DEFAULT NULL COMMENT '角色描述',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0-禁用，1-启用',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0-未删除，1-已删除',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='角色表';

CREATE TABLE menu (
    menu_id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '菜单ID',
    menu_name VARCHAR(50) NOT NULL COMMENT '菜单名称',
    path VARCHAR(200) DEFAULT NULL COMMENT '路由路径',
    component VARCHAR(200) DEFAULT NULL COMMENT '组件路径',
    icon VARCHAR(50) DEFAULT NULL COMMENT '图标',
    parent_id BIGINT NOT NULL DEFAULT 0 COMMENT '父菜单ID',
    sort INT NOT NULL DEFAULT 0 COMMENT '排序',
    type TINYINT NOT NULL DEFAULT 1 COMMENT '类型：0-目录，1-菜单，2-按钮',
    permission VARCHAR(100) DEFAULT NULL COMMENT '权限标识',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0-禁用，1-启用',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0-未删除，1-已删除',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='菜单表';

CREATE TABLE user_role (
    user_id BIGINT NOT NULL COMMENT '用户ID',
    role_id BIGINT NOT NULL COMMENT '角色ID',
    PRIMARY KEY (user_id, role_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户角色关联表';

CREATE TABLE role_menu (
    role_id BIGINT NOT NULL COMMENT '角色ID',
    menu_id BIGINT NOT NULL COMMENT '菜单ID',
    PRIMARY KEY (role_id, menu_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='角色菜单关联表';

CREATE TABLE community (
    community_id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '小区ID',
    name VARCHAR(100) NOT NULL COMMENT '小区名称',
    address VARCHAR(200) DEFAULT NULL COMMENT '地址',
    map_lng DOUBLE DEFAULT NULL COMMENT '经度',
    map_lat DOUBLE DEFAULT NULL COMMENT '纬度',
    total_building INT DEFAULT 0 COMMENT '楼栋数量',
    total_house INT DEFAULT 0 COMMENT '房屋数量',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0-禁用，1-启用',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0-未删除，1-已删除',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='小区表';

CREATE TABLE camera (
    camera_id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '摄像头ID',
    name VARCHAR(100) NOT NULL COMMENT '名称',
    ip_address VARCHAR(50) DEFAULT NULL COMMENT 'IP地址',
    community_id BIGINT NOT NULL COMMENT '小区ID',
    location VARCHAR(200) DEFAULT NULL COMMENT '位置描述',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0-离线，1-在线',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0-未删除，1-已删除',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='摄像头表';

CREATE TABLE person (
    person_id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '居民ID',
    community_id BIGINT NOT NULL COMMENT '小区ID',
    user_name VARCHAR(50) NOT NULL COMMENT '姓名',
    mobile VARCHAR(20) DEFAULT NULL COMMENT '手机号',
    sex VARCHAR(10) DEFAULT NULL COMMENT '性别',
    house_no VARCHAR(50) DEFAULT NULL COMMENT '门牌号',
    person_type VARCHAR(20) DEFAULT 'owner' COMMENT '类型：owner-业主，tenant-租户',
    face_url VARCHAR(500) DEFAULT NULL COMMENT '人脸照片URL',
    state TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0-禁用，1-正常',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0-未删除，1-已删除',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='居民表';

CREATE TABLE in_out_record (
    record_id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '记录ID',
    person_id BIGINT DEFAULT NULL COMMENT '居民ID',
    person_name VARCHAR(50) NOT NULL COMMENT '姓名',
    community_id BIGINT NOT NULL COMMENT '小区ID',
    type VARCHAR(10) NOT NULL COMMENT '类型：in-进入，out-离开',
    time VARCHAR(30) DEFAULT NULL COMMENT '时间',
    location VARCHAR(200) DEFAULT NULL COMMENT '位置',
    photo_url VARCHAR(500) DEFAULT NULL COMMENT '抓拍照片URL',
    verified TINYINT NOT NULL DEFAULT 1 COMMENT '验证状态：0-未验证，1-已验证',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0-未删除，1-已删除',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='出入记录表';

CREATE TABLE visitor (
    visitor_id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '访客ID',
    person_id BIGINT DEFAULT NULL COMMENT '被访人ID',
    name VARCHAR(50) NOT NULL COMMENT '访客姓名',
    mobile VARCHAR(20) DEFAULT NULL COMMENT '手机号',
    id_card VARCHAR(30) DEFAULT NULL COMMENT '身份证号',
    community_id BIGINT NOT NULL COMMENT '小区ID',
    visit_time VARCHAR(30) DEFAULT NULL COMMENT '来访时间',
    leave_time VARCHAR(30) DEFAULT NULL COMMENT '离开时间',
    reason VARCHAR(200) DEFAULT NULL COMMENT '来访原因',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0-已离开，1-在访',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0-未删除，1-已删除',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='访客表';

CREATE TABLE operation_log (
    log_id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '日志ID',
    user_id BIGINT NOT NULL COMMENT '用户ID',
    username VARCHAR(50) NOT NULL COMMENT '用户名',
    module VARCHAR(50) DEFAULT NULL COMMENT '操作模块',
    operation VARCHAR(50) DEFAULT NULL COMMENT '操作类型',
    method VARCHAR(200) DEFAULT NULL COMMENT '请求方法',
    params TEXT DEFAULT NULL COMMENT '请求参数',
    ip VARCHAR(50) DEFAULT NULL COMMENT 'IP地址',
    time BIGINT DEFAULT NULL COMMENT '执行耗时(ms)',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='操作日志表';

SET FOREIGN_KEY_CHECKS = 1;
